# Standard Flutter Podfile for Truefit Coaches
platform :ios, '13.0'

# Standard path to podhelper.rb
load File.expand_path(File.join('Flutter', 'podhelper.rb'), __dir__)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      # Align deployment target to 13.0 for all pods
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
